# Generated by Django 4.2.6 on 2023-10-27 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='de_txt',
            new_name='dt_txt',
        ),
    ]
